/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for qat_rsapubkey
 */
#include <linux/asn1_decoder.h>

extern const struct asn1_decoder qat_rsapubkey_decoder;

extern int qat_rsa_get_e(void *, size_t, unsigned char, const void *, size_t);
extern int qat_rsa_get_n(void *, size_t, unsigned char, const void *, size_t);

